### ISSUE TITLE
App crashes immediately

### ISSUE THREAD

**Issue by amilopowers** [guerda/Matekarte#3]
On Nexus 5 Android 4.4.4, Omnirom.

**Comment by tuxbox** [comment]
The issue seems to be a Nullpointer, as I had the same problem after compiling and deploying it to a Nexus 4 with Android 5.0.1.
I have just forked the app for various reasons, and that should be fixed on the way as well. I hope to submit a pull request later this week. However the API seems to have changed the initial list cannot be populated and the server returns a 500 - Internal Server error on the initial request.
Are you aware of any good API documentation?

**Comment by guerda** [comment]
Hi @tuxbox !
Thank you very much for your interest and the fork!
Some days ago, I commited a fix for the NullPointerException on startup and I also fixed the 500 error. Unfortunately, now all mate dealers are downloaded at startup, as the geospatial request is currently not supported anymore by the API.
The API is not documented, I found out about most of the functions via network traffic analysis in Firefox (Firebug or built-in developer tools). I do stand in contact with the developer of Matekarte.de and he is interested in this app.
So if you want to contribute to Matekarte App, please just drop me a mail, then we can chat about it!

Kind regards,
Philip
